### ISSUE TITLE
As a user I want to view a list of all the tagged terms so that I can learn about the topics on the tree and navigate to the tree through the tags

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#66] opened 2023-02-06 15:08 UTC

**Comment by gissoo** [comment] 2023-03-01 00:15
@rlskoeser @jhimpele please review the proposed design for the [tag index page here on Figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=960%3A1132&t=peT75mT4UTb9ILte-1) – 
Notes:
- Please also read the notes on Figma  (they are mainly for Rebecca)
- Rebecca, you can get a lot of the information I've included on the notes by inspecting the autolayout on Figma too. 
- The idea is to display the tags in two columns on desktop, and one column on mobile which is 768px and below. 
- I've placed the count information inside the tag containers.

**Comment by jhimpele** [comment] 2023-03-01 15:57
@gissoo 
a few notes for you:

.the alpha ordering in two columns looks good.
.we are going to change that long Susquehanna...tag to something shorter, like Midwest

.question 1: can we put parens around the count number:  eg. Unami (3). This seems more common in my experiences. 
.question 2: what is the expected behavior when a user clicks a tag from this page?

**Comment by gissoo** [comment] 2023-03-01 20:47
@jhimpele thank you for writing! We could put them in parentheses, I started with them but eliminated because they were adding too much noise/clutter and slightly increasing the lengths of the tag containers. 

@jhimpele thank you for bringing that up – part of me wanted to explicitly close issue #55 on tag interactions before discussing this. [Please review here on Figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=968%3A1653&t=Tlx43gtgtWDAr0FD-1) – Based on our discussion on the other issue and Rebecca's point I agree that the logic shared above would make sense here. If you select a tag from the tag index page you'll see all the leaves that share the tag with **no** **specific** **leaf** **selected** – I think you wouldn't see the project intro here, but I don't feel strongly if you prefer that it would be visible.

**Comment by jhimpele** [comment] 2023-03-02 17:57
@gissoo Let's use your original inclination to use parens. Ok?

@gissoo Thanks - so the view would switch away from the tag index to the tree? Also, it does make sense not to include the intro but would the panel be blank? What does that look like?

**Comment by rlskoeser** [comment] 2023-03-02 19:33
This all looks good to me generally. I like the two columns / one column, and numbers inside the tag buttons. I like the interaction flow as you have it documented.

I strongly prefer parens around the counts.

It would be easier for me to display the introduction on desktop when we link to the tree with a tag selected; the intro never actually goes away on desktop, it just gets covered by the leaf details when a leaf is selected. Does behavior need to match on mobile? I think it's slightly easier to have the intro collapsed in that case.

I'm a little confused by your text description of the alpha order — but if it matches the logic as you have it in the mockup then that works for me.

**Comment by gissoo** [comment] 2023-03-06 21:20
@rlskoeser @jhimpele I'm ok with displaying the intro panel when you view the leaves of a selected tag. I've updated designs, [so now you can see what this interaction looks like on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1002%3A1998&t=Eh0m0fXGygvTXTfr-1). please take a look and let me know what you think. The main difference between mobile and desktop here is the "x" and the "i" buttons for closing and opening the intro panel on mobile.

**Comment by gissoo** [comment] 2023-03-06 21:22
@rlskoeser @jhimpele thank you for the feedback! 
- I've added the parenthesis. It makes my calculations a little off, but not enough for me to revise them. 
- I'm ok with displaying the intro panel when you view the leaves of a selected tag/seems logical to me. I've updated the designs, [so now you can see what this interaction looks like on mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1002%3A1998&t=Eh0m0fXGygvTXTfr-1). please take a look and let me know what you think. The main difference between mobile and desktop here is the "x" and the "i" buttons for closing and opening the intro panel on mobile.

**Comment by jhimpele** [comment] 2023-03-07 16:01
This is interesting. If we didn’t see the Intro panel there, what otherwise would be visible?


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 3/6/23, 4:22 PM, "gissoo" wrote:

I'm ok with displaying the intro panel when you view the leaves of a selected tag/seems logical to me.

**Comment by rlskoeser** [comment] 2023-03-07 20:05
@gissoo this looks great!

I'm not convinced the project intro should be displayed on mobile — or at least, should be possible to close the intro and keep the tag active so you can use more of the screen to explore the tree. Any concerns? Can the tag be at the bottom of the page if/when intro is closed?

Do we have any tags that will be longer than the width of the panel? Or has that been addressed in the recent tag cleanup?  (Wondering if I will need to have logic to truncate / wrap.)

**Comment by gissoo** [comment] 2023-03-07 22:29
@rlskoeser @jhimpele I'm ok with not seeing the intro panel on mobile – that makes sense to me especially because of the space limitations. I prefer to not have it be there at all rather than display it and then enable closing it. I have revised the designs, [take a look and let me know what you think ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1002%3A1491&t=Fpe6Sg5esVGcHSxY-1) 

1. I propose that when the tag is active you wouldn't be able to scroll through the page down to the footer. (the page rather stays focused on the tree, we can discuss when we talk about mobile) – once the tag is closed then then you can scroll through the page. 


2. once at the stage below, I propose that selecting the "i" would open the project intro panel while keeping the tag on top of it in order to make the experience more consistent between mobile and desktop. 
<img width="627" alt="Screenshot 2023-03-07 at 5 27 09 PM" src="https://user-images.githubusercontent.com/44615389/223567912-e6496e7b-396b-4771-ab3d-1375c9aa6f91.png">

**Comment by rlskoeser** [comment] 2023-03-07 22:31
@gissoo thanks for updating! These decisions all sound good to me.

**Comment by gissoo** [comment] 2023-03-07 22:32
@rlskoeser regarding your question on the length of the longest tag, the last tag in the design below was the longest one and it didn't exceed the width of any of the panels (desktop/mobile), and Jeff has since revised this tag. So I don't think we'll have anything this long either. 
<img width="311" alt="Screenshot 2023-03-07 at 5 31 16 PM" src="https://user-images.githubusercontent.com/44615389/223568665-c0a2adc8-865e-4c70-b138-b6070dc21bc9.png">

**Comment by gissoo** [comment] 2023-03-07 22:36
@rlskoeser however, I'm not sure if we'll need to truncate once a tag is active like the style below 
<img width="576" alt="Screenshot 2023-03-07 at 5 35 54 PM" src="https://user-images.githubusercontent.com/44615389/223569504-9b9d2b93-32b6-4fe2-b9f3-610595dd61f7.png">

**Comment by jhimpele** [comment] 2023-03-08 14:15
A new contender for the longest tag! 
@gissoo all of these decisions look good to me.

**Closed** 2023-03-08 15:56 UTC
Labels: 💬 awaiting review, 🗺️ design
